version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_PORT_EUREKA=8761
    ports:
      - "8761:8761"
